apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - zipkin-deployment.yaml
  - service-discovery-deployment.yaml
  - cloud-config-deployment.yaml
  - sonarqube-deployment.yaml

commonLabels:
  app.kubernetes.io/part-of: ecommerce-microservices
  app.kubernetes.io/component: core
