apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager-webhook
  template:
    metadata:
      labels:
        app: alertmanager-webhook
    spec:
      containers:
        - name: webhook
          image: ghcr.io/tarampampam/webhook-tester:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: HTTP_PORT
              value: "8080"
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 20m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-webhook
spec:
  type: NodePort
  selector:
    app: alertmanager-webhook
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32080

