apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api-gateway-deployment.yaml
  - order-deployment.yaml
  - payment-deployment.yaml
  - product-deployment.yaml
  - shipping-deployment.yaml
  - user-deployment.yaml
  - favourite-deployment.yaml
  - proxy-client-deployment.yaml

commonLabels:
  app.kubernetes.io/part-of: ecommerce-microservices
  app.kubernetes.io/component: business-services
