apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /order-service/actuator/prometheus
        prometheus.io/port: "8300"
    spec:
      containers:
      - name: order-service
        image: selimhorri/order-service-ecommerce-boot:0.1.0
        ports:
        - containerPort: 8300
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        - name: SPRING_ZIPKIN_BASE_URL
          value: "http://zipkin:9411"
        - name: SPRING_ZIPKIN_ENABLED
          value: "false"
        - name: MANAGEMENT_TRACING_SAMPLING_PROBABILITY
          value: "0.0"
        - name: LOGGING_LEVEL_ROOT
          value: "WARN"
        - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
          value: "health,info,metrics,prometheus"
        - name: MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED
          value: "true"
        - name: MANAGEMENT_HEALTH_LIVENESSSTATE_ENABLED
          value: "true"
        - name: MANAGEMENT_HEALTH_READINESSSTATE_ENABLED
          value: "true"
        - name: SPRING_CONFIG_IMPORT
          value: "optional:configserver:http://cloud-config:9296/"
        - name: EUREKA_CLIENT_REGION
          value: "default"
        - name: EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT
          value: "myzone"
        - name: EUREKA_CLIENT_SERVICEURL_MYZONE
          value: "http://service-discovery:8761/eureka"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://service-discovery:8761/eureka/"
        - name: EUREKA_CLIENT_ENABLED
          value: "true"
        - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
          value: "true"
        - name: JAVA_TOOL_OPTIONS
          value: "-XX:MaxRAMPercentage=40 -Xms128m -Xmx200m"
        startupProbe:
          httpGet:
            path: /order-service/actuator/health
            port: 8300
          periodSeconds: 10
          failureThreshold: 90
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /order-service/actuator/health/liveness
            port: 8300
          initialDelaySeconds: 180
          periodSeconds: 45
          failureThreshold: 4
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /order-service/actuator/health/readiness
            port: 8300
          initialDelaySeconds: 90
          periodSeconds: 15
          failureThreshold: 4
          timeoutSeconds: 10
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "400Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
  - port: 8300
    targetPort: 8300
  type: NodePort
