apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway
  labels:
    app: api-gateway
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-service
  labels:
    app: user-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-service
  labels:
    app: order-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payment-service
  labels:
    app: payment-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: product-service
  labels:
    app: product-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shipping-service
  labels:
    app: shipping-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: favourite-service
  labels:
    app: favourite-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: proxy-client
  labels:
    app: proxy-client
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-discovery
  labels:
    app: service-discovery
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloud-config
  labels:
    app: cloud-config

